name: Terraform

on:
  push:
    branches: main
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'

jobs:
  terraform-validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check for terraform version mismatch
        run: |
          DOTFILE_VERSION=$(cat .terraform-version)
          TERRAFORM_IMAGE_REFERENCES=$(grep "uses: docker://hashicorp/terraform" .github/workflows/terraform.yml | grep -v TERRAFORM_IMAGE_REFERENCES | wc -l | tr -d ' ')
          if [ "$(grep "docker://hashicorp/terraform:${DOTFILE_VERSION}" .github/workflows/terraform.yml | wc -l | tr -d ' ')" != "$TERRAFORM_IMAGE_REFERENCES" ]
          then
            echo -e "\033[1;31mError: terraform version in .terraform-version file does not match docker://hashicorp/terraform versions in .github/workflows/terraform.yml"
            exit 1
          fi

      - name: Validate Terraform docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          config-file: .terraform-docs.yml
          output-file: README.md
          output-method: inject
          fail-on-diff: true

      - name: Remove azure backend
        run: rm ./backend.tf

      - name: Run a Terraform init
        uses: docker://hashicorp/terraform:1.11.4
        with:
          entrypoint: terraform
          args: init

      - name: Run a Terraform validate
        uses: docker://hashicorp/terraform:1.11.4
        with:
          entrypoint: terraform
          args: validate

      - name: Run a Terraform format check
        uses: docker://hashicorp/terraform:1.11.4
        with:
          entrypoint: terraform
          args: fmt -check=true -diff=true

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.44.1

      - name: Run TFLint
        run: tflint -f compact
